version: "3.8"

services:
  web:
    expose:
      - 8080
    volumes:
      - .:/code
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - MONGO_USERNAME=${MONGO_USERNAME}
        - MONGO_PASSWORD=${MONGO_PASSWORD}
        - MONGO_HOST=mongo
        - MONGO_DATABASE=${MONGO_DATABASE}
  
  reverse_proxy:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  mongo:
    image: mongo:3.4.4
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./Data/mongo:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE : ${MONGO_DATABASE}
