FROM nginx:1.19.1-alpine

RUN apk update
RUN apk add --no-cache openssl
RUN openssl req -x509 -nodes -days 365  -subj  "/C=CA/ST=QC/O=Dailymotion/CN=api.dailymotion" -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt;

